name: Shopping-List-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test_UNIT:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Run UNIT Tests
      run: npm run test:unit
    - name: Display Softuni Username
      run: echo "monstersbg"
  build_and_test_UI:

      runs-on: ubuntu-latest
      needs: build_and_test_UNIT

      steps:
      - uses: actions/checkout@v4
      - name: Use Node.js version 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Install playwright
        run: npx playwright install
      - name: Start application
        run: npm run start &
      - name: Run UI Tests
        run: npm run test:ui
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to production
          uses: johnbeynon/render-deploy-action@v0.0.8
          with:
            service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
            api-key: ${{ secrets.MY_RENDER_API_KEY }}